<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260511224528 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, designation VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE commentaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(20) NOT NULL, contenu TEXT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, personne_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67F068BCA21BD112 ON commentaire (personne_id)');
        $this->addSql('CREATE TABLE peinture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(20) NOT NULL, largeur NUMERIC(10, 2) NOT NULL, hauteur NUMERIC(10, 2) NOT NULL, en_vente BOOLEAN NOT NULL, prix NUMERIC(10, 2) NOT NULL, date_realisation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description TEXT NOT NULL, personne_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8FB3A9D6A21BD112 ON peinture (personne_id)');
        $this->addSql('CREATE TABLE peinture_categorie (peinture_id INT NOT NULL, categorie_id INT NOT NULL, PRIMARY KEY (peinture_id, categorie_id))');
        $this->addSql('CREATE INDEX IDX_38CEF7CFC2E869AB ON peinture_categorie (peinture_id)');
        $this->addSql('CREATE INDEX IDX_38CEF7CFBCF5E72D ON peinture_categorie (categorie_id)');
        $this->addSql('CREATE TABLE personne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(20) NOT NULL, pre_nom VARCHAR(20) NOT NULL, tel NUMERIC(15, 0) NOT NULL, cin VARCHAR(8) NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (emaillogin VARCHAR(50) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649681B9B8E ON "user" (emaillogin)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCA21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE peinture ADD CONSTRAINT FK_8FB3A9D6A21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE peinture_categorie ADD CONSTRAINT FK_38CEF7CFC2E869AB FOREIGN KEY (peinture_id) REFERENCES peinture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE peinture_categorie ADD CONSTRAINT FK_38CEF7CFBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649BF396750 FOREIGN KEY (id) REFERENCES personne (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BCA21BD112');
        $this->addSql('ALTER TABLE peinture DROP CONSTRAINT FK_8FB3A9D6A21BD112');
        $this->addSql('ALTER TABLE peinture_categorie DROP CONSTRAINT FK_38CEF7CFC2E869AB');
        $this->addSql('ALTER TABLE peinture_categorie DROP CONSTRAINT FK_38CEF7CFBCF5E72D');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649BF396750');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE commentaire');
        $this->addSql('DROP TABLE peinture');
        $this->addSql('DROP TABLE peinture_categorie');
        $this->addSql('DROP TABLE personne');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
